### PR TITLE
Update to goblin master (0.0.7) and fixes issue #6

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by malbarbo** [comment]
I should have return an Err instead of panning... Should I update the PR?

**Comment by m4b** [comment]
Wow thanks for the work! We can ignore the windows CI error, I dunno how to set it up :laughing:. So I just realized:

1. The major changes are in the goblin "pe" branch, if you're feeling adventurous, you can try building off that. The major addition are moving from hacky io errors to a unified error type, and moving from Read generics to [Pread/Gread](https://github.com/m4b/scroll) Because sym uses quick error, should be able to fix error issues this with a simple from line, similar the other froms: https://github.com/m4b/cargo-sym/blob/master/src/errors.rs#L12
2. Fixing to use generics from scroll should lead to simpler code, but is the tedious part I'm talking about. I haven't reviewed yet the extent of changes
3. Goblin will require rust 1.15 which won't land until 2/2/2017 (next week basically), so I wouldn't merge into master here and release until goblin 0.0.7 is on crates which requires scroll and scroll_derive to be on crates which all require rust 1.15.

But in the meantime all this can be ready to go off with a button push when 1.15 does drop, by changing the goblin DEP from git branch to crates.

Also release next week means cargo sym will also stop working on stable, so good to be ready.

That's a mouthful, I know!

Let me know if you have any questions. Also if you're bored and/or don't feel like fixing it up, that's fine too :)

**Comment by m4b** [comment]
Yes, definitely need to return error instead of panic, but probably makes more sense to just start on integrating with upstream PE branch changes I think

**Comment by malbarbo** [comment]
Update to use goblin/pe branch.

I write what I think is the minimum necessary to make it compiles, but the point 2 must be worked.

Maybe this is enough to make a new release when 1.15 got release. I'm afraid that I cannot finish the upgrade to the new errors and the generic read of scroll.

I tested `cargo-sym` on the stable, beta and nightly and it is working.

**Comment by m4b** [comment]
This looks great, thanks!

So yes, for two, will require more invasive changes, and this seems to be the minimal working set, which I'm OK with.  Refactoring to not use cursors will be nice and will make the code more maintainable imho, but not critical.

What's important is that there's a working version for the new changes with a new goblin for rust 1.15, which looks to be the case. Great job!

I will merge this but not sure if I'll wait to stable released, I'll think about it tonight :)

**Comment by m4b** [comment]
Going to merge; should compile on stable in a week, @malbarbo thanks so much!

**Pull request merged**
